spring: 
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: mf-oauth
          uri: lb://mf-oauth
          predicates:
            - Path=/oauth2/**
          filters:
            - CacheFilter
            # 验证码处理
            - CheckCodeFilter
            - StripPrefix=1
        # 测试中心
        - id: mf-test
          uri: lb://mf-test
          predicates:
            - Path=/test/**
          filters:
            # 验证码处理
            # - CheckCodeFilter
            - StripPrefix=1    
        - id: mf-code
          uri: lb://mf-code
          predicates:
            - Path=/code/**
          filters:
            # 验证码处理
            # - CheckCodeFilter
            - StripPrefix=1       
# 安全配置
security:
  # 验证码
  captcha:
    enabled: true
    type: math
    checkUrls:
      - /oauth2/authorize
  # 防止XSS攻击
  xss:
    enabled: true
    excludeUrls:
  # 不校验白名单
  ignore:
    whites:
      - /oauth2/**
      - /code/**
      - /*/v2/api-docs